name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v0.1.0)'
        required: true
        default: 'v0.3.1'

env:
  NODE_VERSION: '18'

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Check if packages exist and are ready
        run: |
          echo "Checking package builds..."
          ls -la packages/core/dist/
          ls -la packages/react/dist/
          ls -la packages/icons/dist/
          echo "Core package info:"
          cat packages/core/package.json | jq '.name, .version'
          echo "React package info:"
          cat packages/react/package.json | jq '.name, .version'
          echo "Icons package info:"
          cat packages/icons/package.json | jq '.name, .version'

      - name: Publish core package
        working-directory: packages/core
        run: |
          echo "Publishing @pixelforge-ui/core..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish icons package
        working-directory: packages/icons
        run: |
          echo "Publishing @pixelforge-ui/icons..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish react package
        working-directory: packages/react
        run: |
          echo "Publishing @pixelforge-ui/react..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}